name: Deploy Sample Data to S3 mirror
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    if: github.repository == 'sunpy/sample-data'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
        - uses: actions/checkout@v2
          lfs: true

        - name: Generate Indices
          run: |
            ls
            ls sunpy/v1/
            bash generate_index.sh > index.html
            bash sunpy/generate_index.sh > sunpy/index.html
            bash sunpy/v1/generate_index.sh > sunpy/v1/index.html

        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: ./
            bucket: data.sunpy.org
            bucket-region: "eu-west-1"
